/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.ArticleController;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Article;
import model.LigneFacture;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class FactureView extends javax.swing.JFrame {

    /**
     * Creates new form Facture
     */
    public FactureView() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPanelFactureAchats = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonAfficheVente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListFactureVente = new javax.swing.JTable();
        jButtonHome1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonAchat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListOfFactureAchats = new javax.swing.JTable();
        jButtonHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Invoice Management System");

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facture");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPanelFactureAchats.setBackground(new java.awt.Color(0, 0, 255));
        jTabbedPanelFactureAchats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPanelFactureAchats.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPanelFactureAchats.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAfficheVente.setBackground(new java.awt.Color(0, 51, 204));
        jButtonAfficheVente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAfficheVente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAfficheVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-refresh-30 (1).png"))); // NOI18N
        jButtonAfficheVente.setText("Refresh");
        jButtonAfficheVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficheVenteActionPerformed(evt);
            }
        });

        jTableListFactureVente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Num Fact", "Nom Client", "Article", "Libelle", "Prix", "Quantite", "Total"
            }
        ));
        jTableListFactureVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListFactureVenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListFactureVente);

        jButtonHome1.setBackground(new java.awt.Color(0, 0, 255));
        jButtonHome1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButtonHome1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\JavaAppGestionFacture\\src\\images\\icons8-home-30 (1).png")); // NOI18N
        jButtonHome1.setText("Home");
        jButtonHome1.setBorder(null);
        jButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAfficheVente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAfficheVente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanelFactureAchats.addTab("Facture de Vente", jPanel1);

        jButtonAchat.setBackground(new java.awt.Color(0, 0, 204));
        jButtonAchat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAchat.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAchat.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\JavaAppGestionFacture\\src\\images\\icons8-refresh-30 (1).png")); // NOI18N
        jButtonAchat.setText("Refresh");
        jButtonAchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAchatActionPerformed(evt);
            }
        });

        jTableListOfFactureAchats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Num Fact", "Nom Fournisseur", "Article", "Libelle", "Prix", "Quantite", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTableListOfFactureAchats);

        jButtonHome.setBackground(new java.awt.Color(0, 0, 255));
        jButtonHome.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\JavaAppGestionFacture\\src\\images\\icons8-home-30 (1).png")); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.setBorder(null);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanelFactureAchats.addTab("Facture d'achat", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelFactureAchats)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPanelFactureAchats)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonAfficheVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficheVenteActionPerformed
     // Récupérer les données à partir de la BDD via le contrôleur
    ArticleController ac = new ArticleController();
    ArrayList<Article> articles = ac.getAll(); // Récupère la liste des articles
    LigneFacture lf = new LigneFacture();

    // Créer le modèle de tableau
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Id");
    model.addColumn("Numéro Facture");
    model.addColumn("Nom Client");
    model.addColumn("Article");
    model.addColumn("Libellé");
    model.addColumn("Prix");
    model.addColumn("Quantité");
    model.addColumn("Total");

    // Mettre à jour la JTable avec le modèle
    jTableListFactureVente.setModel(model);

    // Récupérer les factures et afficher dans le tableau
    String url = "jdbc:mysql://localhost:3306/gestionfactures";
    String login = "root";
    String pwd = "";
    double totalGlobal = 0.0;

    try {
        // Connexion à la base de données
        Connection conn = DriverManager.getConnection(url, login, pwd);

        // Requête pour récupérer les factures
        String query = "SELECT f.id, f.numFact, f.nomClient, lf.article_id, lf.quantite, a.libelle, lf.prix " +
                       "FROM facturevente f " +
                       "JOIN ligneFacture lf ON f.id = lf.article_id " +
                       "JOIN article a ON lf.article_id = a.id";

        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Ajouter les données dans la JTable
        while (rs.next()) {
            int id = rs.getInt("id");
            String numFacture = rs.getString("numFact");
            String nomClient = rs.getString("nomClient");
            int articleId = rs.getInt("article_id");
            String libelle = rs.getString("libelle");
            double prix = rs.getDouble("prix");
            int quantite = rs.getInt("quantite");

            // Calcul du total pour la ligne
            double total = prix * quantite;

            // Ajouter une ligne dans le modèle de la JTable
            Object[] row = new Object[]{
                id,
                numFacture,
                nomClient,
                articleId, // Affichage de l'ID de l'article
                libelle,
                prix,
                quantite,
                total
            };
            model.addRow(row);
            totalGlobal += total;
        }

         Object[] totalRow = new Object[]{"", "", "", "", "", "Total Global", "", totalGlobal};
        model.addRow(totalRow);
       
        // Fermer la connexion
        rs.close();
        stmt.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    // Appliquer le modèle à la JTable
    jTableListFactureVente.setRowHeight(25);
    jTableListFactureVente.setModel(model);    
        
    }//GEN-LAST:event_jButtonAfficheVenteActionPerformed

    private void jButtonAchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAchatActionPerformed
        // TODO add your handling code here:
    String url = "jdbc:mysql://localhost:3306/gestionfactures";
    String login = "root";
    String pwd = "";

    // Créer le modèle de tableau
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Id");
    model.addColumn("Numéro Facture");
    model.addColumn("Nom Fournisseur");
    model.addColumn("Article Id");
    model.addColumn("Quantité");
    model.addColumn("Libellé");
    model.addColumn("Prix");
    model.addColumn("Total");

    jTableListOfFactureAchats.setModel(model);  // Assurez-vous que la table est vide avant d'ajouter les données

    double totalGlobal = 0.0;
   
    try {
        // Connexion à la base de données
        Connection conn = DriverManager.getConnection(url, login, pwd);

        // Requête pour récupérer les factures d'achat et leurs lignes
        String query = "SELECT f.id, f.numFact, f.nomfour, lf.article_id, lf.quantite, a.libelle, lf.prix " +
                       "FROM factureachat f " +
                       "JOIN ligneFacture lf ON f.id = lf.article_id " +
                       "JOIN article a ON lf.article_id = a.id";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        // Parcourir les résultats et les ajouter au modèle de tableau
        while (rs.next()) {
            String id = rs.getString("id");
            String numFacture = rs.getString("numFact");
            String nomFournisseur = rs.getString("nomfour");
            String articleId = rs.getString("article_id");
            int quantite = rs.getInt("quantite");
            String libelle = rs.getString("libelle");
            double prix = rs.getDouble("prix");
            double total = quantite * prix; // Calcul du total

            // Ajouter une ligne dans le tableau
            Object[] row = new Object[]{id, numFacture, nomFournisseur, articleId, quantite, libelle, prix, total};
            model.addRow(row);
              totalGlobal += total;
        }

         Object[] totalRow = new Object[]{"", "", "", "", "", "Total Global", "", totalGlobal};
        model.addRow(totalRow);

       
        // Appliquer le modèle à la JTable
        jTableListOfFactureAchats.setModel(model);
        jTableListOfFactureAchats.setRowHeight(25);

       
        // Fermer la connexion et les ressources
        rs.close();
        stmt.close();
        conn.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erreur de connexion à la base de données : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonAchatActionPerformed

    private void jTableListFactureVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListFactureVenteMouseClicked
       

    }//GEN-LAST:event_jTableListFactureVenteMouseClicked

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHome1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonHome1ActionPerformed
     


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactureView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAchat;
    private javax.swing.JButton jButtonAfficheVente;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonHome1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPanelFactureAchats;
    private javax.swing.JTable jTableListFactureVente;
    private javax.swing.JTable jTableListOfFactureAchats;
    // End of variables declaration//GEN-END:variables
}
